#!/bin/bash

if [[ $1 == "--train" ]] 
then 
	cmake . -B build &&
	cmake --build build --config RelWithDebInfo -j 16 && 	
	./build/testbed --scene data/nerf/cholec80/
elif [[ $1 == "--metrics" ]]  
then
	python scripts/run.py --scene cholec80 --test_transform /home/skhalid/Documents/instant-ngp/data/nerf/cholec80/transforms.json 
elif [[ $1 == "--colmap" ]]
then
	python scripts/colmap2nerf.py --colmap_matcher sequential --run_colmap --aabb_scale 16 --out ./data/nerf/cholec80/transforms.json
else
	echo "No input provided"
fi
